route:
  group_by: [Alertname]
  # Send all notifications to me.
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - to: 'xxxx@gmail.com'
    from: yyyy@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: yyyy@gmail.com
    auth_identity: yyyy@gmail.com
    auth_password: xxxxxxxxxxx
    send_resolved: true

